site_name: "Atlas Framework Docs"
repo_url: https://github.com/renderbox/atlas-framework
watch: [src/atlas, docs]

nav:
  - "index.md"
  - "api.md"
  - "change_notes.md"
  # - Coverage report: coverage.md

theme:
  name: "material"

plugins:
  - search
  # - coverage:
  #     page_name: coverage # default
  #     html_report_dir: htmlcov # default
  - mkdocstrings
