site_name: "Atlas Framework Docs"
repo_url: https://github.com/renderbox/atlas-framework
watch: [src/atlas, docs]
docs_dir: docs

nav:
  - "index.md"
  - "change_notes.md"
  - "getting_started.md"
  - "installed_app.md"
  - "pyside2app.md"
  - API Reference: reference/
  # - Coverage report: coverage.md

theme:
  name: "material"

plugins:
  - search
  - gen-files:
      scripts:
        - "docs/gen_ref_pages.py"
  - literate-nav:
      nav_file: SUMMARY.md
  # - mkdocstrings

  # - coverage:
  #     page_name: coverage # default
  #     html_report_dir: htmlcov # default
