name: Build and Deploy Docs

on:
  push:
    branches: ["develop"]
  # release:
  #   types: [published] # Docs should be updates on version published
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-gen-files mkdocs-literate-nav mkdocstrings[python]
        # coverage[toml] mkdocs-coverage

      # - name: Generate Coverage report
      #   run: |
      #     coverage html

      - name: Build documentation
        run: |
          # Build your documentation
          # For example, if you're using MkDocs, create a mkdocs.yml configuration file in your repository root
          # Then run the following command:
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
