name: Build and Deploy Docs

on:
  release:
    types: [published] # This should not update unless a version is published

  push:
    branches:
      - main # or the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install package
        run: |
          pip  .

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings[python]

      - name: Build documentation
        run: |
          # Build your documentation
          # For example, if you're using MkDocs, create a mkdocs.yml configuration file in your repository root
          # Then run the following command:
          mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/
